name: cuarta_ruta_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  logger: ^2.6.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon_black.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf